### ISSUE TITLE
mf strings not rendering with browser-policy default setting

### ISSUE THREAD

**Issue by brylie** [gadicc/meteor-messageformat#104]
When installing the [browser-policy](https://atmospherejs.com/meteor/browser-policy) package, all MF translation strings become unavailable. There seems to be a default security setting in browser-policy that prevents MF from working. How can I diagnose this problem to configure the correct security settings?

**Comment by gadicc** [comment]
You need to `BrowserPolicy.content.allowEval();` - unfortunately in v0 we require `eval()` to generate the functions on the client.  You'll be happy to know however that in v2 we've already worked around this, but it will be some time until v2 is out.

**Comment by brylie** [comment]
Thanks @gadicc! :-)

**Comment by gadicc** [comment]
sure :)
