### ISSUE TITLE
Separate all UI text from the template code

### ISSUE THREAD

**Issue by bajiat** [gadicc/meteor-messageformat#108]
One of the basic rules of internationalisation is to separate all UI text from the code. You are already using unique keys to identify text, so maybe it would be worthwhile not to have the "native" or original language in the template code. Treat the native language as a variant just like the languages that are translated.

See also
[10 Internationalization tips for developers – I18N checklist](http://www.emreakkas.com/internationalization/10-internationalization-tips-for-developers-i18n-checklist)
Go to section: Externalize all translatable content – Take the text out of the code and place in resource files

**Comment by sbalmer** [comment]
If you don't want to provide a default translation, there's no need to add it. It's optional after all. Personally I find it very helpful to have default translations. They allow rapid developement while providing an example string for translators.

The tip you mention doesn't cover the possibility of having a default translation. They're using resource files in the example which is arguably quite primitive compared to the tooling this project offers. Note the gettext examples further down. gettext uses translatable strings as keys, and it's a widely used library.

**Comment by DSpeichert** [comment]
As @sbalmer mentioned, the default translation is optional. This allows developers to externalize all translations right now. I don't see a need for additional changes to comply with the referenced "checklist".
