### ISSUE TITLE
[v2] debug trace

### ISSUE THREAD

**Issue by DSpeichert** [gadicc/meteor-messageformat#112]
```
TypeError: Cannot read property 'updatedAt' of undefined
    at localeStringsCompiled (packages/msgfmt:core/lib/mfPkg/messageformat-server.js:346:1)
    at Object.Package [as handle] (packages/msgfmt:core/lib/mfPkg/messageformat-server.js:399:1)
    at next (/home/spigu/bundle/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at Object.out [as handle] (packages/msgfmt:core/lib/mfPkg/messageformat-server.js:297:1)
    at next (/home/spigu/bundle/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at Object.WebApp.rawConnectHandlers.use.contentTypeOptions [as handle] (packages/browser-policy-common/browser
-policy-common.js:28:1)
    at next (/home/spigu/bundle/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
    at middleware (packages/oauth/oauth_server.js:157:1)
    at packages/oauth/oauth_server.js:146:1
```

**Comment by gadicc** [comment]
Hey, can you double check that you have all the latest versions?  I noticed that shortly after we spoke this issue and pushed a fix... otherwise i'll look into it early next week, just away for the weekend.

**Comment by DSpeichert** [comment]
You might be right, I'll test...

**Comment by DSpeichert** [comment]
Still a problem in preview.5.

**Comment by gadicc** [comment]
Oh last thing to try before i can look into this again...  Make sure you're calling msgfmt.init('en') and if you weren't before, resave any files your keys need to be extracted from..  But yeah this needs to be a lot more resillient. 

On 02 May 2015 12:24:56 AM SAST, Daniel Speichert <notifications@github.com> wrote:
>```
>TypeError: Cannot read property 'updatedAt' of undefined
>at localeStringsCompiled
>(packages/msgfmt:core/lib/mfPkg/messageformat-server.js:346:1)
>at Object.Package [as handle]
>(packages/msgfmt:core/lib/mfPkg/messageformat-server.js:399:1)
>at next
>(/home/spigu/bundle/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
>at Object.out [as handle]
>(packages/msgfmt:core/lib/mfPkg/messageformat-server.js:297:1)
>at next
>(/home/spigu/bundle/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
>at Object.WebApp.rawConnectHandlers.use.contentTypeOptions [as handle]
>(packages/browser-policy-common/browser
>-policy-common.js:28:1)
>at next
>(/home/spigu/bundle/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
>    at middleware (packages/oauth/oauth_server.js:157:1)
>    at packages/oauth/oauth_server.js:146:1
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/gadicc/meteor-messageformat/issues/112

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by DSpeichert** [comment]
```js
msgfmt.init('en', {
    sendPolicy: 'all'
});
```
on both client & server.

**Comment by gadicc** [comment]
I can't reproduce on my end but I made some changes which I think should fix this... when you get a chance, if you could confirm with the latest v2/master that would be great.  Thanks :)

**Comment by gadicc** [comment]
Actually I published core.6 since then :>

**Comment by DSpeichert** [comment]
It looks like it's fixed!

**Comment by gadicc** [comment]
Great stuff, love it when I'm not sure for sure that I fixed something and I did :)

**Comment by gadicc** [comment]
Thanks.

**Comment by DSpeichert** [comment]
Haha!
