### ISSUE TITLE
[v2] Translation not loading in offline mode on startup msgfmt.setLocale(); does not work 

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#113]
Testing out the patched version 2, everything loads fine but if the user is offline and does a page refresh the langue does not load, I'm calling msgfmt.setLocale();. But I run Session.set('locale', getUserLanguage()); then everything is fine. 

It seems that msgfmt.setLocale(); can't load the correct lang when offline

**Comment by gadicc** [comment]
hey almog, I think `msgfmt:core@2.0.0-preview.6` will solve this issue for you.  i tested on a deployment (messageformat-v2.meteor.com) and it loads instantly with the last used language.  definitely a big improvement over v0 :)

**Comment by almogdesign** [comment]
Works great now with the latest versions
