### ISSUE TITLE
V2  TypeError: Cannot read property 'connection' of undefined

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#115]
I'm getting the following error with V2 

 TypeError: Cannot read property 'connection' of undefined
W20150505-14:26:41.181(3)? (STDERR)     at mf (packages/msgfmt:core/lib/mfPkg/messageformat.js:88:1)
W20150505-14:26:41.181(3)? (STDERR)     at app/lib/tabular_datatables.js:10:41
W20150505-14:26:41.181(3)? (STDERR)     at app/lib/tabular_datatables.js:45:3
W20150505-14:26:41.181(3)? (STDERR)     at /Users/macbookpro/GoPlatfarm/RnD/App/platfarm-app/.meteor/local/build/programs/server/boot.js:222:10
W20150505-14:26:41.181(3)? (STDERR)     at Array.forEach (native)
W20150505-14:26:41.182(3)? (STDERR)     at Function._.each._.forEach (/Users/macbookpro/.meteor/packages/meteor-tool/.1.1.3.uamjhn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150505-14:26:41.182(3)? (STDERR)     at /Users/macbookpro/GoPlatfarm/RnD/App/platfarm-app/.meteor/local/build/programs/server/boot.js:117:5

**Comment by gadicc** [comment]
Can you confirm if you're on `msgfmt:core@2.0.0-preview.6`?  This was fixed in https://github.com/gadicc/meteor-messageformat/commit/d70cf59c60b97af7cdf6712609650182a848a3a1, where you should get a warning instead.

Using `mf()` on the server outside of a publish/method and without specifying a locale probably isn't what you want, but it will now default to the native language.

**Comment by almogdesign** [comment]
I'm on the following 

msgfmt:core                         2.0.0-preview.3* MessageFormat support, the Meteor way
msgfmt:extract                      2.0.0-preview.3* Extracts native / translatable strings from your app
msgfmt:ui                           2.0.0-preview.2  messageformat: translation UI

Will update and check

**Comment by gadicc** [comment]
Sorry I got these two threads confused, my original answer in https://github.com/gadicc/meteor-messageformat/issues/116#issuecomment-99114195 was what I meant for here.  But either way it's relevant for both.  Let's just stick to all the latest versions.

**Comment by almogdesign** [comment]
Works great with latest versions
