### ISSUE TITLE
[v2] Exception in callback of async function: TypeError: Object 1430825246316 has no method 'getTime'

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#116]
I'm getting the following error with v2

I20150505-14:27:26.319(3)? 2015-05-05 14:27:26.316 info:  [msgfmt:extracts]  4 string(s) added, 0 changed, and 2 marked as removed.
I20150505-14:27:26.356(3)? Exception in callback of async function: TypeError: Object 1430825246316 has no method 'getTime'
I20150505-14:27:26.356(3)?     at packages/msgfmt:extract/extract.js:148:1
I20150505-14:27:26.356(3)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
I20150505-14:27:26.797(3)? Kadira: successfully authenticated

**Comment by gadicc** [comment]
Should be fixed in `msgfmt:extract@2.0.0-preview.5`.

**Comment by almogdesign** [comment]
I'm on 

msgfmt:core                         2.0.0-preview.3* MessageFormat support, the Meteor way
msgfmt:extract                      2.0.0-preview.3* Extracts native / translatable strings from your app
msgfmt:ui                           2.0.0-preview.2  messageformat: translation UI

Which version should I update to?

**Comment by gadicc** [comment]
I guess you can remove the `@=` for everything and just go for `@` for now.  And then `meteor update`.  In some cases releases were made to address some of your other issues, e.g. https://github.com/gadicc/meteor-messageformat/issues/113#issuecomment-98751325.

**Comment by gadicc** [comment]
Oh, sorry if I wasn't clear... When I said "should be fixed in extract.5" what I meant was, "I've just fixed this and published the fix as extract.5, please try it" :)  Sometimes I'm too short :>

**Comment by almogdesign** [comment]
Not sure I understand you can't do meteor update with "@" 
I was able to update msgfmt:extract but not core or UI what version should I be using? 

msgfmt:core                         2.0.0-preview.3* MessageFormat support, the Meteor way
msgfmt:extract                      2.0.0-preview.5  Extracts native / translatable strings from your app
msgfmt:ui                           2.0.0-preview.2  messageformat: translation UI

**Comment by gadicc** [comment]
Oh, I might be wrong but I think I once told you to use `@=` when adding the packages (and consequently in `.meteor/packages` which would lock to that specific version and prevent upgrades.  If you change it to just an `@`, you should be able to upgrade it.  You want `msgfmt:core@2.0.0-preview.6`.

**Comment by almogdesign** [comment]
I had to run meteor remove and then meteor add I'm on the following versions now are they correct? 
msgfmt:core                         2.0.0-preview.6  MessageFormat support, the Meteor way
msgfmt:extract                      2.0.0-preview.5  Extracts native / translatable strings from your app
msgfmt:ui                           2.0.0-preview.2  messageformat: translation UI

**Comment by gadicc** [comment]
Yup!  Let me know how it goes.

**Comment by almogdesign** [comment]
works great closing

**Comment by gadicc** [comment]
Yay! :)
