### ISSUE TITLE
[v2] setLocale() but no getLocale()

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#117]
You have setLocale() but not an option for knowing which local lang is loaded?

**Comment by gadicc** [comment]
`msgfmt.locale()` :)

it's reactive and mentioned in the "Reactivity" section of the [README](https://github.com/gadicc/meteor-messageformat/tree/v2).  there are a few others too.

**Comment by almogdesign** [comment]
Ok great I was on the website

**Comment by gadicc** [comment]
Ah ok no worries... the website will be out of date until a stable release comes out.
