### ISSUE TITLE
[v2] msgfmt.locale() and msgfmt.lang() not working 

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#118]
I'm getting the following error  
TypeError: Object #<Object> has no method locale 
TypeError: Object #<Object> has no method lang

I'm just doing a simple console log in shared code (lib folder)
console.log(msgfmt.locale());

**Comment by gadicc** [comment]
Wait, that's not working on the client?

That will always fail on the server, there's no reactivity on the server.
Inside of a method/publish you can get the locale from `this.connection.locale`.
That's used automatically by `mf()` on the server.

**Comment by almogdesign** [comment]
Forgot to set the isClient check, works great now
