### ISSUE TITLE
[v2] Ground.Collection(msgfmt.mfStrings); Ground.Collection(msgfmt.mfMeta);

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#120]
With v2 do I still need to set the following on common code before the msgfmt init 

Ground.Collection(msgfmt.mfStrings);
Ground.Collection(msgfmt.mfMeta);

**Comment by gadicc** [comment]
Nope.  v2 handles all it's own offline support internally.  You don't need to do anything on your side to make it work.

**Comment by almogdesign** [comment]
great will remove
