### ISSUE TITLE
[v2] Meteor Message Format does not work with Meteor Cordova Android  

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#131]
I tried publishing my app using Meteor Cordova Android. I got a number of errors starting with Meteor Message Format. Once I removed the package everything was fine. I take it message format is not supported in Meteor Cordova.

**Comment by almogdesign** [comment]
@gadicc is there any plans to support this with a hotfix before v2? We're running into issues with GroundDB on Chrome and looking towards Mobile

**Comment by gadicc** [comment]
Yes, I'm aiming for full Cordova support in the stable release.  We'll see if we cover everything I have planned for Cordova, but at the very least we'll make sure it's useable with no errors.

Haven't had a chance to look at this on Cordova yet, can you paste the error?

**Comment by almogdesign** [comment]
I don't have the errors had to remove the package it would not compile with Message Format I can add it back but best you try to compile it firs on your end

**Comment by dcsan** [comment]
@almogdesign maybe you can add the error here at least, that could save gadi some time?

**Comment by almogdesign** [comment]
@dcsan sure will try to get back to testing this next week

**Comment by Slanman3755** [comment]
I need this working as well :+1:

**Comment by DSpeichert** [comment]
This should be fixed now as of #191.
