### ISSUE TITLE
[v2] Removing previously existing strings

### ISSUE THREAD

**Issue by tcastelli** [gadicc/meteor-messageformat#137]
Not sure if this a bug or I just did something that I shouldn't, but since i had on the database strings that were no longer needed i manually removed them from the database and then downloaded the new mfall.js. The problem is that i get this error when trying to use this new mfall.js for the first time(the second time i start meteor it works locally but this prevents my deployment in the cloud)

MongoError: '$set' is empty. You must specify a field like so: {$mod: {<field>: ...}}
W20150608-15:23:32.641(2)? (STDERR)     at Object.Future.wait (/home/zzzzz/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20150608-15:23:32.641(2)? (STDERR)     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
W20150608-15:23:32.642(2)? (STDERR)     at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:678:1)
W20150608-15:23:32.642(2)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:575:1)
W20150608-15:23:32.642(2)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:165:1)
W20150608-15:23:32.642(2)? (STDERR)     at Object.mfPkg.langUpdate (packages/msgfmt:core/lib/mfPkg/messageformat-server.js:126:1)
W20150608-15:23:32.643(2)? (STDERR)     at Object.mfPkg.syncAll (packages/msgfmt:core/lib/mfPkg/messageformat-server.js:167:1)
W20150608-15:23:32.643(2)? (STDERR)     at app/server/mfAll.js:1:42
W20150608-15:23:32.643(2)? (STDERR)     at app/server/mfAll.js:13359:3
W20150608-15:23:32.643(2)? (STDERR)     at /home/zzzz/xxx/yyy/.meteor/local/build/programs/server/boot.js:222:10
W20150608-15:23:32.643(2)? (STDERR)     - - - - -

Just in case this is not the way to proceed to delete translated strings, how should i proceed?

**Comment by tcastelli** [comment]
@gadicc Is there any cookbook recipe to delete strings that are no longer needed? Removing the mf from the html/js just takes out the original(let's say english) translation :S
thanks!

**Comment by tcastelli** [comment]
forgot to answer i solved this by getting a backup file of mfall and  complete the missing translations again. Still guessing how can i delete the "marked as delete" strings to avoid unnecesary space, but will open another thread for that

**Comment by gadicc** [comment]
@tcastelli, thanks for reporting back!   You're right, we definitely need a cleaner way to do this.  Please leave the issue open.  I consider this important but not as important as critical use features, so I'm marking it for the v2.1 milestone.  Thanks also for your patience.

**Comment by tcastelli** [comment]
Thanks @gadicc i've just created another post with the feature request, you can close it if you think it will be cleaner! :)

**Comment by gadicc** [comment]
Shweet.   Yeah, I'll leave the new issue in the milestone; iit refers back to this one so I'll be able to track all the related things to think about.
