### ISSUE TITLE
Support for JSX

### ISSUE THREAD

**Issue by zachariahtimothy** [gadicc/meteor-messageformat#138]
Can you add support for JSX? I am using React Meteor and really want to use this library. It seems like the regex that walks JS files just needs to add |jsx in the regex.  
Thanks!

**Comment by gadicc** [comment]
Yes, I think you're right.  PRs welcome :)  Or just a bundle of real life jsx files that I could test against, to make sure it all works like we expect.  Agreed, this is essential moving forward.

**Comment by zachariahtimothy** [comment]
Here is an example JSX file. Since mf() does not work for jsx I have a
wrapper called translate().

var homeFeaturedDestinations = ReactMeteor.createClass({
  templateName: 'HomeFeaturedDestinations',
  startMeteorSubscriptions: function() {
    Meteor.subscribe('destinations');
  },
  getMeteorState: function() {
    return {
      destinations: Destinations.find({}).fetch()
    };
  },
  renderDestination: function (model) {
    model.featured = model.featured || { image: {} };
    return <div key={model._id} className="featured-card
featured-destination-card col-lg-4 col-md-12">
      <a href="#" style={{backgroundImage: 'url(' +
model.featured.image.url + ')'}}>
        <h4 className="text-contract">{translate(model.name)}</h4>
      </a>
    </div>
  },
  render: function () {
    var state = this.state;

    if (!state.destinations) {
      return <p>Loading...</p>
    }
    return <section className="section section-center section-cta">
      <div className="container">
        <h2
className="section-title"><span>{i18n('siteTemplate.homeFeaturedDestinations.title',
'Destinations')}</span></h2>
        <p
className="text-lead">{i18n('siteTemplate.homeFeaturedDestinations.leadText')}</p>
        <div className="row">
          {state.destinations.map(this.renderDestination)}
        </div>
      </div>
    </section>
  }
});


_____________________________________
Zach Curtis
P: 970.590.6383
E: zachariahtimothy@gmail.com
T: @zachariahCurtis <https://twitter.com/#!/@zachariahCurtis>

**Comment by flipace** [comment]
Are there any news to share about this?

**Comment by flipace** [comment]
I forked v2 and added a jsx handler. It works like a charme for my project. I would create a pull request but I'm not sure what a proper test case for this would look like..

**Comment by gadicc** [comment]
@flipace, that's awesome!!  i'm getting a lot stricter on requiring tests, but since particular change won't affect any other part of the stack, and none of our other handlers have tests yet either (that would be easy to emulate), and of course, that a lot of people are dying for this, please go right ahead :)

**Comment by flipace** [comment]
Alright @gadicc I'm going to create the pull request somewhen today!

**Comment by gadicc** [comment]
Awesome!  Thank you :)

**Comment by gadicc** [comment]
Great stuff, many thanks!  Just published in `mf:ui@2.0.0-preview.13`.

**Comment by flipace** [comment]
No problem, if there are any jsx issues in the futuer, I'm happy to help.

**Comment by gadicc** [comment]
Awesome, that will definitely be appreciated... I'm not using JSX yet personally, but I do plan to...  so it's great that messageformat is ahead of me :)
