### ISSUE TITLE
http:/localhost:3000/translate  shows:  "Native language: en (0 strings)"

### ISSUE THREAD

**Issue by tvld** [gadicc/meteor-messageformat#141]
http:/localhost:3000/translate  shows 
> "Native language: en (0 strings)"

Even though:
> mf_extract, v0.0.6
> Project root: /home/tom/Websites/Meteor/my-app
>
> ./client/index.html
>trans_string: "This string is translatable"
>i_am_str: "I am a string."

**Comment by gadicc** [comment]
If you `meteor shell` and type:

```
msgfmt.forceExtract();
```

does that make any difference?

Are you initializing msgfmt on both the server and client with `msgfmt.init('en');` ?

Also, could you please paste the full log from the load sequence?

**Comment by tvld** [comment]
Yesterday I removed package after it failed, but your quick response made me tray again. And where I could not get it working yesterday in 2 hours... now it worked in 5 min....   I cant remember where it went wrong, I suspect msgfmt was not running in server. Two ideas:
1 -  Maybe if the "0 strings"  answer shows, it would be possible to verify correct loading of msgfmt? 
2 - Could there be button to run "mf_extract -v" on /translate page ? Then context / loading can be checked ?
Thanks for quick response, I will continue to use ;)
Tom

**Comment by DSpeichert** [comment]
mf_extract won't be needed at all in v2 and I believe @gadicc does not plan to change the behavior of current version until v2 is "finished".

**Comment by tvld** [comment]
Thanks, So far a bit more of error handling still welcome and looking forward to v2 :)
