### ISSUE TITLE
Use datatables in translator interface?

### ISSUE THREAD

**Issue by tvld** [gadicc/meteor-messageformat#145]
With close to 100 translation strings, growing to 1000+, the /translation interface becomes a bit of a problem: it is difficult to find and sort strings.

Could we use something like https://github.com/aldeed/meteor-tabular ?  If we also include the columns of the KEY  and file-url, we can group & sort columns. The translation-management becomes a more friendly process.

**Comment by gadicc** [comment]
Agreed.  Can & should, with filtering/searching (which that seems to support too).

**Comment by gadicc** [comment]
Hey, we never ended up using meteor-tabular, but I think all of these features gradually made it into msgfmt:ui on their own, so I'm closing for now.  Assuming you're on v2, let us know how the changes have affected your experience.

**Comment by tvld** [comment]
We have scaled down our Meteor developments in the light of the unsure future with React/Blaze and so on. We might come back if Meteor is on track again... but for now using other tools such as Aurelia :)  Thanks for the effort though )

**Comment by gadicc** [comment]
Thanks for the update, @tvld.  Yes, I'm in this boat too.  My next project is going to use arunoda's/kadira's mantra.  I think MDG is going in the right direction (but a little too late, and too slow); if I'm wrong though, it shouldn't be difficult to migrate a mantra app away from Meteor.  We'll see how 2016 plays out though and what direction meteor messageformat takes.

**Comment by tvld** [comment]
For some reason, I cant really get my head around Mantra. I feel there is potential, but maybe I am seeing it as having not enough cloud to dive into it. That is my fault I suppose )
Well... waiting a bit might solve a lot I agree ;)

**Comment by gadicc** [comment]
I don't think it's obvious at all :)  But I have a lot of faith in Arunoda.  The two core principles of 1) High maintanability and 2) future-proof are very appealing, if it works.  I need to get comfortable with it and see how it feels using for an actual project.  Then of course see how React ecosystem develops into something more comfortable and prevalent into Meteor ecosystem.  Will be an interesting year :)
