### ISSUE TITLE
V2 - ReferenceError: Logger is not defined

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#151]
Just installed v2 on a brand new app and when I run meteor I'm getting the following error 

ReferenceError: Logger is not defined
W20150814-04:16:03.192(3)? (STDERR)     at out (packages/msgfmt:extract/extract.js:221:1)

**Comment by almogdesign** [comment]
I had to remove all packages, is this build working?

**Comment by almogdesign** [comment]
Anyone can really use some help here?

**Comment by almogdesign** [comment]
I tried to manually add meteor add logging but this did not help

**Comment by almogdesign** [comment]
I also tried 

meteor add msgfmt:core@=2.0.0-preview.12
meteor add msgfmt:extract@=2.0.0-preview.8
meteor add msgfmt:ui@=2.0.0-preview.2

**Comment by gadicc** [comment]
Hey, sorry for the lack of contact, I'm away on holiday at the moment.  Amazingly, @DSpeichert already fixed this in https://github.com/gadicc/meteor-messageformat/tree/1ec002648381888bbbf837c07e8648fe58f3af33 but we just didn't publish to Atmosphere yet.  You can now:

```
meteor add msgfmt:extract@=2.0.0-preview.9
```

and it should all work.

**Comment by almogdesign** [comment]
Great thanks will test it out now

**Comment by almogdesign** [comment]
Everything is working thanks
