### ISSUE TITLE
V2 - Support Flow Router 

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#152]
Any plans to support flow router?

**Comment by DSpeichert** [comment]
I assume that applies to msgfmt:ui only?

**Comment by almogdesign** [comment]
Yes it would only apply to that, it looks like flow router or something similar might be part of meteor core and everyone is moving towards flow router

**Comment by gadicc** [comment]
Hey, https://github.com/gadicc/meteor-messageformat/pull/133 actually addresses this, but now there is a package https://github.com/nicolaslopezj/meteor-router-layer that provides router agnostic routing support for packages... we will definitely be switching over to use this so that we'll always support all popular Meteor routers without needing to worry about writing the code ourselves.

**Comment by almogdesign** [comment]
Sweet

**Comment by flipace** [comment]
This doesn't work for me yet. This is an issue with router layer though since it doesn't use existing Routers correctly.

**Comment by gadicc** [comment]
Oh :(  Is there an issue open with router-layer about it?  Ideally we can fix this once for everyone.

I had tested with flow-router, but just the /translate pages.  I didn't see how it interacted with the rest of a site using it.

**Comment by tdesc** [comment]
Hello,
I also moved from iron:router to flow-router since last Meteor version update.
Adding router-layer doesn't help. ```There is no route for the path: /translate```
Is there any kind of workaround?

**Comment by flipace** [comment]
@tdesc this was/is my temporary workaround: https://www.dropbox.com/s/7uahrtwxuzl62vf/msgfmt-ui-flow-router.zip?dl=0

**Comment by flipace** [comment]
@tdesc it would be [project root]/packages/msgfmt:ui

**Comment by tdesc** [comment]
Looks like I'm doing something wrong
I have <b>gadicohen:messageformat, kadira:flow-router </b>  and <b>/packages/msgfmt:ui</b>

**Comment by tdesc** [comment]
@gadicc Could you please create empty project with  gadicohen:messageformat and kadira:flow-router? I'm still can't make it work.

**Comment by gadicc** [comment]
hey all, apologies that I haven't been able to spend more time on this recently.

@tdesc, the flow-router support is only in v2.  sorry that I didn't notice this from your messages earlier.  I've released a new version of v2 now that warns if v0 is still installed.

@flipace, PRs are always welcome :)  what did you change?  it's working for me.

**Comment by DSpeichert** [comment]
I am closing this as it is working (for some at least) in v2.
If there is any more issues with flow-router  support through `nicolaslopezj/meteor-router-layer`, feel free to reopen.

**Comment by gadicc** [comment]
Yes, if anyone else is still having issues, please let us know.
