### ISSUE TITLE
[V2] getting weird error when clicking Download server/mfAll.js 

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#153]
This is the error 

Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions. at Object.Meteor.userId (packages/accounts-base/accounts_server.js:19:1) at Object.Meteor.user (packages/accounts-base/accounts_server.js:24:1) at [object Object].requireVerifiedUser (app/lib/router.js:89:23) at packages/iron:router/lib/router.js:277:1 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) at [object Object].hookWithOptions (packages/iron:router/lib/router.js:276:1) at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1) at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1) at packages/meteor/dynamics_nodejs.js:121:1 at [object Object].dispatch (packages/iron:middleware-stack/lib/middleware_stack.js:275:1)

**Comment by DSpeichert** [comment]
Can't reproduce. Probably a relic of v2 development.
