### ISSUE TITLE
[V2] Question Autoform 

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#154]
I'm using the autoform package and it's working great but not reactive is there a way to make it reactive?

**Comment by Maxhodges** [comment]
https://github.com/gadicc/meteor-messageformat/wiki/messageFormat-with-autoform

**Comment by gadicc** [comment]
Thanks, @Maxhodges!  Looks great!

For an all template approach, I think the new Blaze [sub expressions](https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md#nested-sub-expressions) in Meteor 1.2 (when it's released) will make this a lot easier (but I haven't tried yet!).

    {{> afQuickField name='productName' value=preProductName label=(mf 'productLabel' 'My label')}}

Of course, still need to add support for this in our parser too :>

**Comment by Maxhodges** [comment]
OK to close I suppose

**Comment by DSpeichert** [comment]
Closing as fixed in #180
