### ISSUE TITLE
[V2] as a translator, the /translate tool should save when I click Back to Translation Summary

### ISSUE THREAD

**Issue by Maxhodges** [gadicc/meteor-messageformat#155]
In the /translate tool, if I click an 'original string', enter a translation, then click 'Back to Translation Summary' it will lose my work.

It seems you must first click on another item in the original string list in order to save your work. I feel clicking 'Back to Translation Summary' should also trigger a save action.

Cheers!

**Comment by Maxhodges** [comment]
![image](https://cloud.githubusercontent.com/assets/957271/9422223/79dbab4a-48c6-11e5-87c4-825fa4c84f1e.png)

**Comment by 1u** [comment]
+1

**Comment by gadicc** [comment]
Right you are.  Fixed.  Actually, for any page change, we now save the current string (clicking any link, back button to get back to language index, etc).  Will be in next release.
