### ISSUE TITLE
[V2] sometimes translate tool goofs up and links get scrambled

### ISSUE THREAD

**Issue by Maxhodges** [gadicc/meteor-messageformat#156]
here I can't click one of my 'original strings' and some that I can click resolve to the wrong strings

http://screencast.com/t/p7mbfSzlc

also 
http://screencast.com/t/1zZbwd8PL2

You can see the labels I click on are not the labels it opens in the editor. It's like the ordinal index numbers for the rows got messed up or something. A refresh fixed it, but there must be for bug for this to happen in the first place.

Have been able to reproduce by just translating a few original strings, after working on a few, it suddenly gets messed up, but refreshing browser will sort it out.

**Comment by Maxhodges** [comment]
OK I've been trying to translate dozens of strings and this issue with the strings getting scrambled is definitions very repeatable. It's happening after every few edits I made.

**Comment by Maxhodges** [comment]
@gadicc  are you on any kind of donation system? I'd donate if it might help accelerate development. We're trying to bring our app to Chinese soon, and would love to use messageFormat2 for the task!

**Comment by gadicc** [comment]
Thanks for the screencasts!  Really helpful.

I think this might have had to do with #158 (HTML in orig strings) which has now been fixed.  For good measure, I made a slight improvement to the click code anyways.  Will be in next release (next few days) and you can report back.

No donation system unfortunately... I can't really put any more time into this than I already do, but, I do use the code in all my own projects so it is all maintained, and I do find time for occasional sprints.  v2 is slowly getting closer to stable.

In other news, I've actually just started learning Japanese, so this was quite cool to see :)

**Comment by Maxhodges** [comment]
cool! I've published several top selling products for learning Japanese. A few here:
http://www.amazon.com/Max-Hodges/e/B002BMED6C

can I send you a getting started pack? Send me your ship-to address: max attomarku whiterabbitjapan dotto com

**Comment by gadicc** [comment]
hey @Maxhodges, that's very kind!  What a nice twist of face :>  I've just emailed you, much appreciated ^_^

**Comment by 1u** [comment]
same error here. thank you for fixing it!

There is some hope, we have Japanese translation of [Openki](https://github.com/schuel/hmmm) soon :) That's kind of funny!
Happy learning

**Comment by gadicc** [comment]
@1u, Japanese ftw!  arigatou :)  Wait so can you confirm this is fixed in the new version?  `mf:ui@2.0.0-preview.4` ?

**Comment by Maxhodges** [comment]
yes yes sorry for delay. We used it today for Chinese work and it was working fine!
