### ISSUE TITLE
[V2] translate tool fails to display original strings with html

### ISSUE THREAD

**Issue by Maxhodges** [gadicc/meteor-messageformat#158]
I have some html tags in 'original strings' (used to format text in a bootstrap3 popover). These strings fail to display in the top section of the translate tool. 

![image](https://cloud.githubusercontent.com/assets/957271/9425172/60603570-4941-11e5-93d4-37bedcae8172.png)

**Comment by DSpeichert** [comment]
v0 or v2 or both?

**Comment by Maxhodges** [comment]
we are using v2!

**Comment by gadicc** [comment]
Oh wow, that's no good :>  I refactored a lot of this stuff for the [router agnosticism work](https://github.com/gadicc/meteor-messageformat/issues/152), and will make sure the next preview release properly includes HTML too.

**Comment by gadicc** [comment]
Mmm, was already fixed with the abovementioned commit :)  Will be in next release.
