### ISSUE TITLE
[V2] question: does ES2015 template strings have implications for messageFormat

### ISSUE THREAD

**Issue by Maxhodges** [gadicc/meteor-messageformat#160]
https://developers.google.com/web/updates/2015/01/ES6-Template-Strings?hl=en

Just thinking about how this could work with messageFormat. Seems to be a game changer!

**Comment by gadicc** [comment]
Most immediately, multi line strings will be very welcome for longer MessageFormat strings.

Re template strings specifically, I guess we can have a short form like:

    mf`Hello {firstName} etc`

which alleviates the need to specify all the variables again.

Definitely worthy of more discussion.  Doesn't affect templates though, which are the most common use case.  I haven't seen exactly how people are using mf() with React yet (but there's an open issue for jsx support).
