### ISSUE TITLE
First messageformat use prerequisite

### ISSUE THREAD

**Issue by euqip** [gadicc/meteor-messageformat#172]
I tried to use the messageformat module for meteor, with the basic meteor app just created by meteor create myapp.
After having changed the contents of myapp.html with the {{mf 'key' 'string to translate'}}, it was impossible to use any translation before having installed the iron:router module.

Now it's possible to open the translation page, but no update is possible without having a defined logged in user.  The changes in the file are rejected, due to unknown user.

Could you please define if there are prerequisites, modules to install, to use the messageformat moduule?

Many thanks

**Comment by tcastelli** [comment]
Have a look at http://messageformat.meteor.com/docs "Security" section, you must tell the package which user can translate by using allow or deny methods. (By default only logged in users can edit)
in v2 you use msgfmt instead of mfPkg.

**Comment by euqip** [comment]
Thanks for your answer.
I thought that it was possible to translate and receive an application page in user's language before any user is identified.
In between I tried also to use an other package, tap:i18n to have a translated page.  this module has no translation UI, making it hardest to use but instead of limit translations to specific key-value pairs, any translation is usable everywhere with only one definition.  I will try with msgfmt too, and with a defined logged in user.

**Comment by tcastelli** [comment]
you can make that anonymous users can translate the application page, for that, you should do 
what I've said before.
For example you could place (both client and server side) something like this code and it will allow that anyone can see the translate page (deny is false for everyone and allow is true for everyone)
`````javascript
mfPkg.webUI.deny(function(b){
return false;
});

mfPkg.webUI.allow(function(b){
return true;
});
````

msgfmt is the actually the same project, just the next version of mfPkg (v2) and it includes different benefits like automatic extraction of strings. You can read more about it by visiting https://github.com/gadicc/meteor-messageformat/tree/v2  (read how to migrate from v0 to v2)

**Comment by DSpeichert** [comment]
It seems like msgfmt:ui no longer requires iron:router, it depends on `nicolaslopezj:router-layer` instead. I believe the possibly missing prerequisite is no longer an issue.
