### ISSUE TITLE
[v2] msgfmt:ui-dev-only uses ui preview 02 -> involves deprecated packages

### ISSUE THREAD

**Issue by tcastelli** [gadicc/meteor-messageformat#173]
After updating meteor to 1.2 and updating all msgfmt packages I've found that adding ui-dev-only is not updated, since this is what happens

Changes to your project's package version selections:

meteor-platform                added, version 1.2.3
msgfmt:ui+                        added, version 2.0.0-preview.4
msgfmt:ui-dev-only+         added, version 2.0.0-preview.1
nicolaslopezj:router-layer  added, version 0.0.11

not sure about router-layer, but meteor-platform shouldn't be there, hopefully updating package definition will solve this :)

**Comment by DSpeichert** [comment]
Fixed in 5ec9b3335f642d9f1ba9366d34d19a555dfcbec1
