### ISSUE TITLE
Browser policy issue

### ISSUE THREAD

**Issue by loevda** [gadicc/meteor-messageformat#181]
Hi,

I'd like to know if there is any way to make it works with Browser policy?

Thanks

**Comment by DSpeichert** [comment]
@loevda Is there any restriction that does not work for you? I remember that in v0 I had to allow `unsafe-eval` but that was fixed in v2 I think.

**Comment by loevda** [comment]
Hi,

thanks for the reply and sorry for being late but I was away. Is v2 ready for production?
Anyway the fix (unsafe-eval) is working.

Thanks

**Comment by DSpeichert** [comment]
@loevda See #150
