### ISSUE TITLE
duplicate key error

### ISSUE THREAD

**Issue by 1u** [gadicc/meteor-messageformat#184]
If switching back from V2.core.preview15 to older version it crashes.

    MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: meteor.mfStrings.$_id_  dup key: { : "X3uRkrps5czzNuk3n" }

To solve the problem one can then delete the file `extracts.msgfmt` and drop mf_ collections

**Comment by 1u** [comment]
Addition: The problem of creating mixed-up keys is not solved, only the crash on server side. 
Even when deleting extracts.msgfmt~ and `meteor reset` the problem consists. Switching back to core 14...

**Comment by gadicc** [comment]
Sorry, only got back to the office today.  I think there was a race condition here that was made severely worse with the async changes.  I think I've just fixed it though.  Can you backup your database and try `core.16`?

**Comment by 1u** [comment]
jup, seems better!  :)  thx
