### ISSUE TITLE
[ui] Table height should be adjustable.

### ISSUE THREAD

**Issue by gadicc** [gadicc/meteor-messageformat#198]
Via https://github.com/gadicc/meteor-messageformat/issues/40#issuecomment-39810626 (@DSpeichert):

> UI table height should be adjustable.

**Comment by DSpeichert** [comment]
The table - its height is fixed I think? Or maybe make it longer by default, if it is resizable now (don't really remember at the moment and I don't have UI deployed in production).

**Comment by gadicc** [comment]
Ah ok got it.  Updated.  Yes, that's reasonable.  For the textareas, Chrome at least let's the user resize them.
