### ISSUE TITLE
Cordova Android

### ISSUE THREAD

**Issue by loevda** [gadicc/meteor-messageformat#205]
Hi,

I have problem with Android. 

I have the following error:
I20160202-21:48:22.942(1) (android:http://meteor.local/packages/msgfmt_core.js:3541) Uncaught TypeError: Cannot read property 'native' of undefined
I20160202-21:48:23.020(1) (android:http://meteor.local/packages/msgfmt_extract.js:15) Uncaught TypeError: Cannot read property 'mfPkg' of undefined
I20160202-21:48:23.020(1) (android:http://meteor.local/packages/msgfmt_ui.js:19) Uncaught TypeError: Cannot read property 'mfPkg' of undefined
I20160202-21:48:23.021(1) (android:http://meteor.local/packages/global-imports.js:43) Uncaught TypeError: Cannot read property 'mfPkg' of undefined

Web app works fine.

I have the following versions installed:
Meteor 1.2.1
msgfmt:core@2.0.0-preview.17
msgfmt:extract@2.0.0-preview.12
msgfmt:ui@2.0.0-preview.10

Any idea where is the problem?

Thanks

**Comment by gadicc** [comment]
Hey, unfortunately I don't have a Cordova setup over here, but did you see this?

https://github.com/gadicc/meteor-messageformat/tree/v2#cordova

(It's talking about http://docs.meteor.com/#/full/meteor_settings.  Docs will be clearer in the final release).

**Comment by loevda** [comment]
Hi,

thanks for the quick reply. I have it all setup inside the settings file as in the doc and passed it with --settings option. I still have the issue. 

Thanks

**Comment by loevda** [comment]
Hi,

I spent all day on this and cannot find a solution-

I have created a new project with just a couple of templates and few packages.

If I remove meteor-messageformat I have no problem launching the app on android avd.
As soon as I add it to the project I have the same problem as in my first post. I have tried to cancel the local folder, wipe out the data from the avd but nothing help. 

**Here is the full list of errors:**
I20160203-20:31:58.710(1) (android:http://meteor.local/packages/msgfmt_core.js:3541) Uncaught TypeError: Cannot read property 'native' of undefined
I20160203-20:31:58.791(1) (android:http://meteor.local/packages/msgfmt_extract.js:15) Uncaught TypeError: Cannot read property 'mfPkg' of undefined
I20160203-20:31:58.791(1) (android:http://meteor.local/packages/msgfmt_ui.js:19) Uncaught TypeError: Cannot read property 'mfPkg' of undefined
I20160203-20:31:58.791(1) (android:http://meteor.local/packages/global-imports.js:14) Uncaught TypeError: Cannot read property 'mfPkg' of undefined
I20160203-20:31:58.791(1) (android:http://meteor.local/app/client/templates/application/template.hello.js:2) Uncaught ReferenceError: Template is not defined

When the app launch I have a white screen that says that it cannot find the "layout" template. 

**Packages list:**
iron:router
msgfmt:core
msgfmt:extract
msgfmt:ui
sacha:spin
twbs:bootstrap
underscore

**Versions (with iron:router, see template issue):**
Meteor 1.2.1
msgfmt:core@2.0.0-preview.17
msgfmt:extract@2.0.0-preview.12
msgfmt:ui@2.0.0-preview.10
iron:controller@1.0.12
iron:core@1.0.11
iron:dynamic-template@1.0.12
iron:layout@1.0.12
iron:location@1.0.11
iron:middleware-stack@1.0.11
iron:router@1.0.12
iron:url@1.0.11

Anybody has any idea?

Thanks

**Comment by MartinFournier** [comment]
@gadicc is it possible that the preview.17 package was not pushed to package store using the code currently in the [messageformat-client.js#L398](https://github.com/gadicc/meteor-messageformat/blob/v2/msgfmt:core/lib/mfPkg/messageformat-client.js#L398) file?

These were the errors I had before making those changes in that file (I am currently using a local package instead of from the meteor repository).

@loevda, Does the msgfmt_core.js file that throws the error has that if (injected) check? If it does not, you can probably make it work if you use the core@2.0.0-preview.17 from a local package (as in clone the repository into the packages folder, remove & then re-add the package)

**Comment by loevda** [comment]
@MartinFournier No the check is not inside the file. I created a local package and the issue is solved on the test project. I'll test my real project tomorrow. Thanks a lot for the help.

**Comment by gadicc** [comment]
@MartinFournier, I would have said that no, that's not possible, except it looks like that's exactly what happened :/  Looking at the commit history, I'm really not sure how.  The PR was merged in, and only after that did I bump the version in `package.js` and publish (that's the commit straight after).  I'm at a loss, but anyway, I've republished and comfirmed that the code is there now.

@loevda, thanks for your patience and helping us figure this out.  For your real project, you can try just `meteor add msgfmt:core@2.0.0-preview.18` now and this should get you up and running.

@MartinFournier, thanks for the extra help, as usual :)

**Comment by loevda** [comment]
@gadicc @MartinFournier thanks to both of you.

**Comment by loevda** [comment]
@gadicc I confirm that msgfmt:core@2.0.0-preview.18 solved it on my project. Thanks a lot again.

**Comment by gadicc** [comment]
Awesome!  Thanks for reporting back :)
