### ISSUE TITLE
language is not changed.

### ISSUE THREAD

**Issue by aviavia** [gadicc/meteor-messageformat#210]
On config.js I have:
msgfmt.init('en', {
    sendPolicy: 'all'
});
navigator.language returns 'he' as expected.

Footer html:
 {{mf 'support' 'Support'}}
{{mf 'privecy' 'privecy'}}
{{mf 'termsOfUse' 'Terms of use'}}
{{mf 'whoWeAre' 'Who we are'}}
and those keys, appear at the list and translated.
Yet the footer links are displayed in English.
Am I missing anything?
Thanks.

**Comment by gadicc** [comment]
Sorry for delay.

Did you try `msgfmt.setLocale('he');` ?

But yes, ideally, we should use or at least the same conclusion as `navigator.language`, I'm surprised we don't.

Can you amend your init like:

``` js
msgfmt.init('en', {
  sendPolicy: 'all',
  logLevel: 'debug'
});
```

and paste the logs from the browser's JavaScript console after a page reload and after typing `msgfmt.resetStorage()` ?

That last step is necessary if your user is logged in with the default `storeUserLocale` option.

**Comment by aviavia** [comment]
It works for me already.
mfPkg.setLocale('he');
I mistakenly replaced mfPkg with a previous name or something, not sure already, thanks.

**Comment by gadicc** [comment]
Ah ok great!  Thanks.
