### ISSUE TITLE
Translate strings from a collection.

### ISSUE THREAD

**Issue by aviavia** [gadicc/meteor-messageformat#211]
Hi,
Assuming I have a small collection, of categories, which is displayed with a select/option element.
Is there a way I can translate it with this plugin? ( or would it be a better idea to add translations at the collection itself? e.g {category_a: {en: '', he: '' , etc: ''}}
Thanks.

**Comment by 1u** [comment]
In [Openki](https://test.openki.net) we have defined the categories in our code here: [categories.js](https://github.com/schuel/hmmm/blob/master/categories.js).
We then translate the strings from our [mfFixedTranslations.html](https://github.com/schuel/hmmm/blob/master/client/lib/mfFixedTranslations.html), and have a helper for them in [here](https://github.com/schuel/hmmm/tree/master/client/views/misc/categories).
I hope this helps :)
#136

**Comment by aviavia** [comment]
Thanks, I don't think it will work for me.

**Comment by gadicc** [comment]
Sorry for the delay.

There is some support for this planned.  I have some code from a private project from a while back which will eventually be cleaned up and make it into it's own msgfmt package.  This is in the distant future though, it definitely won't be before the official 2.0.0 release.

**Comment by gadicc** [comment]
I'll track this in https://github.com/gadicc/meteor-messageformat/issues/136 (thanks @1u).

**Comment by aviavia** [comment]
Thanks, great.
