### ISSUE TITLE
Mixed Content on https (v2)

### ISSUE THREAD

**Issue by Siewart** [gadicc/meteor-messageformat#213]
Hi,

I receive the following error after deploying v2 on our development server.

`0eb9027….js?meteor_js_resource=true:144 Mixed Content: The page at 'https://testapp.test.eu/admin' was loaded over HTTPS, but requested an insecure script 'http://testapp.test.eu/msgfmt/locale/all/0'. This request has been blocked; the content must be served over HTTPS.l @ 0eb9027….js?meteor_js_resource=true:144
`
I guess something internal uses a normal insecure request. 

Any pointers how I could fix this?

**Comment by gadicc** [comment]
Try `msgfmt:core@2.0.0-preview.20` :)

**Comment by Siewart** [comment]
That was an insanely quick fix :D Thanks for that.

**Comment by gadicc** [comment]
Haha, sure, things like these annoy me :>
