### ISSUE TITLE
[V2] extract's JSX handler should allow newlines inside the MF tag

### ISSUE THREAD

**Issue by Sabst** [gadicc/meteor-messageformat#220]
Cannot extract MF information with attributes on different lines .

This works:
`<MF KEY="keyName">My text...</MF>`

But this fails:

```
<MF
  KEY="keyName">My text...</MF>

```

This can be useful to split the line when there are many attributes:

```
<MF
  KEY="keyName"
  ATTR1="attr1"
  ATTR2="attr2"
  ATTR2="attr3">My text...</MF>

```

**Comment by gadicc** [comment]
Right you are!  Fixed with `meteor update` :)

**Comment by Sabst** [comment]
That was fast, thanks!
Looks like this is ok with one new line only.

Here are more tests:

```
<MF KEY='testKey1' ONE={1} TWO={2} THREE={3}>{`Test 1: {ONE} {TWO} {THREE}`}</MF>
<MF
  KEY='testKey2' ONE={1} TWO={2} THREE={3}>{`Test 2: {ONE} {TWO} {THREE}`}</MF>
<MF
  KEY='testKey3'
  ONE={1} TWO={2} THREE={3}>{`Test 3: {ONE} {TWO} {THREE}`}</MF>
<MF
  KEY='testKey4'
  ONE={1}
  TWO={2} THREE={3}>{`Test 4: {ONE} {TWO} {THREE}`}</MF>
<MF
  KEY='testKey5'
  ONE={1}
  TWO={2}
  THREE={3}>{`Test 5: {ONE} {TWO} {THREE}`}</MF>
```

I only see the items 1 and 2.

**Comment by gadicc** [comment]
Sorry... rushed this one out before going away for the long weekend :/  Latest release should finally close this I hope, please confirm.

**Comment by Sabst** [comment]
Just perfect! Thanks a lot!

**Comment by gadicc** [comment]
Great stuff!  Thanks for reporting back.
