### ISSUE TITLE
mf_All.js  removed _id

### ISSUE THREAD

**Issue by 1u** [gadicc/meteor-messageformat#235]
id is removed in mfAll.js. but linked object with this same id remains in collection.
randomly searching, sorry... (tell me if it's annoying :)

same commit: (https://github.com/schuel/hmmm/commit/f2f9e67d390a4a276051ea0aba3b9d4397137adb)

```
     "course.edit.groupUnlistingError": {
-      "_id": "CT4xcjqjH7ZdScT5Y",
       "key": "course.edit.groupUnlistingError",
       "lang": "en",
       "text": "Unable to remove group: {ERROR}",
-      "ctime": "2015-10-14T17:05:17.000Z",
-      "mtime": "2015-10-14T17:05:17.000Z",
-      "revisionId": "KjxRu8DK8f3xLMAB8",
-      "file": "client/views/groups/groupListing.js",
-      "line": 37,
-      "func": "function(err)"
+      "ctime": 1464642609000,
+      "mtime": 1464704870979,
+      "revisionId": "LE4kssXimP2ZyS7hn",
+      "file": "client/views/groups/listing/groupListing.js",
+      "line": 38,
+      "template": "unknown",
+      "removed": true
+    },
```

why is it removed and what happens if key is added again?

**Comment by gadicc** [comment]
Yeah, this is correct; we no longer rely on the `_id` for uniqueness, rather the combination of `key` and `lang`.  This makes it a lot easier to sync between dev and production where the `_id` might be different.

**Comment by gadicc** [comment]
Let me track this with the order in #233.
