### ISSUE TITLE
Cordova iOS Safari error messages

### ISSUE THREAD

**Issue by tdesc** [gadicc/meteor-messageformat#239]
Latest METEOR@1.3.4.1
msgfmt:core msgfmt:extract
tried both msgfmt:ui and msgfmt:ui-dev-only 
Running on iPad device:
White screen with error messages on Safari developer console.

**Comment by tdesc** [comment]
Hello,
As long time MessageFormat fan I want to use it in project production for both Web and Mobile.
I got following error running iOS ( Cordova )

> log.warn('Cordova builds have issues with the inject-initial package, make sure to define settings keys public.localization.native && public.localization.locales');

I can see it checked Meteor.settings.public and Meteor.settings.public.msgfmt
What is correct settings/params to make it work with Cordova?

**Comment by gadicc** [comment]
Hey @tdesc :)  Check https://github.com/gadicc/meteor-messageformat#cordova.

**Comment by tdesc** [comment]
Yeah, thanks! I have only one question regarding languages in this case.
As I understand I should update settings.json "locales": ["en", "fr"]" each time I add new language and restart server?

**Comment by gadicc** [comment]
Yeah, that's right.  I hope one day we'll get this automated again even with Cordova.

**Comment by tdesc** [comment]
Sorry to bother again.

**Comment by tdesc** [comment]
P.S. Just to keep it.
Building iOS project needs 
 run with --settings settings.json solve problem for cordova build.

> meteor run ios-device --mobile-server www.blabla.bla --settings settings.json
