### ISSUE TITLE
No submit button for translations in /translate UI

### ISSUE THREAD

**Issue by monitz87** [gadicc/meteor-messageformat#252]
I'm trying to input new translations in the UI but there is no way of actually submitting them. I searched the repository for the UI html and js files, and there is no visible way to submit translations for my strings. Is there something I'm missing?

**Comment by DSpeichert** [comment]
The only way to add new translations is by putting strings to translate in your code. Then they get detected automatically.
Like this:
```
<h1>{{mf 'heading_welcome' 'Welcome to my Site'}}</h1>
```

**Comment by monitz87** [comment]
I have those, the thing is that when I go to the translation UI I cannot translate them to another language. I'm getting "insert failed: Access denied undefined" in the client

**Comment by DSpeichert** [comment]
Check http://messageformat.meteorapp.com/docs#security

**Comment by monitz87** [comment]
Yeah, my bad, I missed that part. Thanks

**Comment by DSpeichert** [comment]
No problem!

**Comment by monitz87** [comment]
One thing that led to my confusion though, is that you can still access the /translate route even if you aren't allowed to edit it. (For example I wasn't logged in as any user and thus could not insert new translations, but I could still access the interface). Isn't there supposed to be an "error" template that shows if your access is denied?

**Comment by DSpeichert** [comment]
I'm not sure. It's hard because of the different routers, that's why the package is split and you're not forced to use the UI at all. Maybe @gadicc can answer that, I don't really know the code that well anymore.
