### ISSUE TITLE
Split web ui and core messageformat support into separate packages.

### ISSUE THREAD

**Issue by ianserlin** [gadicc/meteor-messageformat#29]
The basic reason is they are two separate pieces of functionality.

The built-in web ui is really excellent to have, of course, but in our case specifically the hard dependency on iron-router (and a specific version) conflicts with the version of iron-router we're using.

Generally, they are solving two different problems - one is the core internationalization, the second is an easy way to provide a GUI for updating translations.

If you'd like help with this just ask, we're definitely interested in using messageformat for all our projects, but we can't at the moment because of the version incompatibilities, as far as I can tell.

Thanks for an awesome package!

**Comment by DSpeichert** [comment]
UI and core are in fact split up for quite a while. Closing this - there are other issues where we track features for UI and they are repetitive.
