### ISSUE TITLE
Amalgamate issues for a "Preview 2" release.

### ISSUE THREAD

**Issue by gadicc** [gadicc/meteor-messageformat#40]
It seems a number of people are using this now and we're ready for a "Preview 2".  Or a possibly even a rc.  What do people think?

Once I hear some thoughts, we can decide on a version number, create a milestone for it, and create/collect all issues relevant for that release (which won't necessarily be "soon", but we can start getting there).

In particular, support for translations from smart packages isn't implemented yet.  There are other examples too.

**Comment by DSpeichert** [comment]
See #73

**Comment by 1u** [comment]
#150

**Comment by gadicc** [comment]
Great, I think a lot of stuff here has been done already or is covered by other issues, which we are tracking with `v2` and `v2.1` milestones.  So, closing this one.
