### ISSUE TITLE
extracting often leads to not allowed state in DB

### ISSUE THREAD

**Issue by piffie** [gadicc/meteor-messageformat#76]
Hi,

i found a bug in the lib.
in the messageformat-server.js you query the local cache if a string is existing.
in the method mfPkg.langUpdate you query this.strings
existing = this.strings[lang][key];

but the strings are not filled before, therefore always empty. An therefore always inserting new ones.
i changed it in my version to get the strings for the whole language before.

cheers

**Comment by DSpeichert** [comment]
@piffie Can you please verify if the same issue affects latest v2 version as released?

**Comment by gadicc** [comment]
I just confirmed that in the current version, `msgfmt.strings` is fully populated before `langUpdate` is first called.  I don't recall how we used to do this before, but we populate `msgfmt.strings` from the database as we load the package (and before msgfmt:extract or mfAll.js is loaded, which would use this function indirectly).
