### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by Helmi** [gadicc/meteor-messageformat#80]
The docs on http://messageformat.meteor.com say:

{{#mf KEY='keyname' VAR1=TemplateVar VAR2=etc}}
    long keytext
{{/#mf}

but should be:

{{#mf KEY='keyname' VAR1=TemplateVar VAR2=etc}}
    long keytext
{{/mf}}

the closing tag should not have a # and the second closing bracket is missing there.

**Comment by gadicc** [comment]
thanks!
