### ISSUE TITLE
Clicking on mfAll.js doesn't work in new iron-router

### ISSUE THREAD

**Issue by gadicc** [gadicc/meteor-messageformat#81]
You get to a translation page for a language called mfAll.js.

**Workaround**

1. Right click the link and click on Save As or Open in New Tab.
OR
1. Type in the URL `/translate/mfAll.js` by hand.

Thanks @helmi for reporting.

**Comment by 1u** [comment]
I also get a  translation page for a language called mfAll.js by klicking on the link but
(with 1. and 2.) In my stored `mfAll.js` file there are not translations anymore, but this:

    ReferenceError: $ is not defined
    at [object Object].Router.map.route.path (app/routing.js:11:2)
    at packages/iron:router/lib/router.js:277:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object].hookWithOptions (packages/iron:router/lib/router.js:276:1)
    at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1)
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
    at packages/meteor/dynamics_nodejs.js:121:1
    at [object Object].dispatch (packages/iron:middleware-stack/lib/middleware_stack.js:275:1)
    at [object Object].RouteController._runRoute (packages/iron:router/lib/route_controller_server.js:63:1)
    at Function.Route.dispatch (packages/iron:router/lib/route.js:147:1)


(https://github.com/schuel/hmmm)  
Is it working for you?  Any help very appreciated... thx

**Comment by 1u** [comment]
Anyone else with this problem?

**Comment by gadicc** [comment]
I suspect this is an iron-router bug but I wasn't able to track it down in the time I had, for now v0.0.48 just includes a workaround which avoids iron-router completely when clicking on this link.  Please can someone else also confirm if this fixes the issue.

**Comment by sbalmer** [comment]
I've investigated the "ReferenceError: $ is not defined" that 1u and me were getting. Turns out the error was in our code.

We have a Router.onBeforAction() that references $ for some client-side stuff, yet it was added on the server-side as well. /translate/mfAll.js now works as expected, clicking the link is no problem.

Sorry for the noise, thanks for the package!

**Comment by almogdesign** [comment]
I'm running into this issue, using the latest version and using iron-router. The following does not work 
Type in the URL /translate/mfAll.js by hand.


and when I try Right click the link and click on Save As I get "failed server problem"

**Comment by almogdesign** [comment]
Is there anyway to download it from the server directly or is it generated? I just spent an hour translating everything

**Comment by almogdesign** [comment]
Here is the error message I'm getting in my logs 

TypeError: Object #<Object> has no method 'page'
    at [object Object].Router.route.name (app/lib/router.js:21:13)
    at packages/iron:router/lib/router.js:277:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object].hookWithOptions (packages/iron:router/lib/router.js:276:1)
    at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1)
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
    at packages/meteor/dynamics_nodejs.js:121:1
    at [object Object].dispatch (packages/iron:middleware-stack/lib/middleware_stack.js:275:1)
    at [object Object].RouteController._runRoute (packages/iron:router/lib/route_controller_server.js:63:1)
    at Function.Route.dispatch (packages/iron:router/lib/route.js:147:1)

**Comment by almogdesign** [comment]
It's also possible there is an issue with app cache as it adds the following to the url - /#!translate

**Comment by gadicc** [comment]
I'm not sure about appcache but if you can't access that URL directly, it's a different problem... I'm going to track it in https://github.com/gadicc/meteor-messageformat/issues/92 since this only deals with iron-router issues.

**Comment by gadicc** [comment]
And yeah the file is generated on request, but don't worry, we'll get to the bottom of this.  All the data is also in the database too.

**Comment by almogdesign** [comment]
Ok I was a bit worried, we're updating production in the 30 to 45 min out client is waiting for this. If its possible to get this fixed by that that would be amazing let me know what I can help with.

**Comment by almogdesign** [comment]
@gadicc I can just copy it to the DB, I'm going to try that

**Comment by gadicc** [comment]
Ok, you have my attention until we get this sorted out.  Most interested in the server error though, if you can paste me the error in https://github.com/gadicc/meteor-messageformat/issues/92 we can work out what's going wrong.  But yeah, copying the mf* collections will have the same effect.

**Comment by almogdesign** [comment]
@gadicc copying the db might not work or will take a long time not sure that's a good idea. 

I'm not getting any errors it possible that was something else when I click on the link I'm getting the following and all the strings are empty 

![screen shot 2015-03-09 at 3 20 47 pm](https://cloud.githubusercontent.com/assets/169507/6555637/34b717bc-c670-11e4-9ce9-a6ab49775455.png)

**Comment by gadicc** [comment]
Yeah don't worry about that, it's showing you translations for a language called "mfAll.js" :>  Because iron-router isn't meant to route that client-side.

Will discuss the rest of it in https://github.com/gadicc/meteor-messageformat/issues/92.
