### ISSUE TITLE
Translation in VCS?

### ISSUE THREAD

**Issue by aermler** [gadicc/meteor-messageformat#82]
I really like this project, it works beautifully! I have a quick question. If I see it correctly the translations are saved in the database. So with a `meteor reset` all my translations would be gone, wouldn't they? Is there a way to keep my translations in a plain text file so I can have it safe in a VCS?

**Comment by gadicc** [comment]
Thanks!  Yup... on the translation page, save the `mfAll.js` file and put it in your `server` directory (just note the recent [issue](https://github.com/gadicc/meteor-messageformat/issues/81) with the latest iron-router).

**Comment by aermler** [comment]
Okay, great, thanks! I didn't see that.
