### ISSUE TITLE
server side translation for a client's current locale

### ISSUE THREAD

**Issue by lucazulian** [gadicc/meteor-messageformat#83]
I'm doing server side validation on a meteor app and I would like to get error messages back to client, localized in the user language (previously set in the client with mfPkg.setLocale("userLanguage")). How can I accomplish this task in the correct way?
On server side the messages are not localized and I'm not sure how to handle this case.

**Comment by MiroRadenovic** [comment]
:+1:

**Comment by gadicc** [comment]
Mmm, that's a good use case and I guess we should provide a pattern for this.

As a starting point, maybe something like:

**client:**

```js
Tracker.autorun(function() {
  Meteor.call('setUserLocale', Session.get('locale');
});
```

**server**:

```js
Meteor.methods({
  setUserLocale: function(locale) {
    this.connection.locale = locale;
  }
});
```

now in every server side method and publish you'll have access to `this.connection.locale`.  The next question is where validation is taking place.  If it's in collection allow/deny methods, I seem to recall these not having access to `this.connection` as a limitation in the Meteor API... iirc Meteor suggested rather working with userIds in this case.  If that's necessary, it's a bit messy but in the setUserLocale method I guess you could just store it in a global, and cleanup with `connection.onClose` in `Meteor.onConnection`.  Did that all make sense? :)

Obviously once you have the locale on the server for that user and/or his/her session, you can just `mf(key [,params] [,message] [,locale]);`.

Let me know if you need complete examples for the middle part, and obviously in any case all of this is untested, so let me know either way.  This seems like something very useful and it will definitely feature in the next major version (which is in the works but still far away).

**Comment by lucazulian** [comment]
@gadicc thanks! I can help you with the effort to put this feature in the next major version. But I need some help to understand the entire library :P. Anyway, the pattern you propose seems reasonable but I don't understand why you need a validation and where this is taking place. I prefer to use the ```userId``` in the allow/deny methods instead of store the ```locale``` in a global, just my 2 cents worth :)

**Comment by lucazulian** [comment]
I have a proposal
in **messageformat-server.js** add 

```
Meteor.methods({
    setUserLocale: function(locale) {
        "use strict";
        this.connection.locale = locale;
    }
});
```

in **messageformat-client.js** add 

```
Tracker.autorun(function() {
    Meteor.call('setUserLocale', Session.get('locale'));
});
```

in **messageforma.js** change the first part of mf function like this

```
mf = function(key, params, message, locale) {
    if (!locale && Meteor.isClient)
        locale = Session.get('locale');
 	if (!locale && Meteor.isServer){
		var currentInvocation = DDP._CurrentInvocation.get();
      	if (currentInvocation) {
			locale = currentInvocation.connection.locale
      	}
 	}
    
    if (!locale) {
        locale = mfPkg.native;
    }
```
In this way I can use mf in server code without track the language of the use in the UI. Did that all make sense? :)

**Comment by gadicc** [comment]
Oh, that's very cool... I didn't think to use DDP._CurrentInvocation.  So that works even in allow/deny functions?  I actually really like that you made this the server default for `mf()` without needing to specify it... that's really intuitive.  This will definitely make it into v2.

**Comment by lucazulian** [comment]
```DDP._CurrentInvocation.get() ``` is not available on allow/deny functions. But just a question: When will the v2 be available for the download?. I ask this because we need this feature as soon as possible, so I can help you in some ways, let me know

**Comment by gadicc** [comment]
v2 has no ETA at the moment unfortunately.  But we have working code above?  It's no problem to use all that in your app code, and to override the main mf() method, I don't see any changes coming to it on the current branch.  In v2 it will just be "official".  I guess you could also just wrap it for now:

```js
var origMf = mf;
mf = function(key, params, message, locale) {
    if (!locale && Meteor.isServer){
        var currentInvocation = DDP._CurrentInvocation.get();
        if (currentInvocation) {
            locale = currentInvocation.connection.locale
        }
    }
    return origMf(key, params, message, locale);
}

**Comment by gadicc** [comment]
Closing since this exists in v2 and all that's left is a bit more docs, tracked in #200.  Thanks again for your contribution here!
