### ISSUE TITLE
Question support for offline mode 

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#84]
Does the translation still work if the app is offline mode (web app) with app cache and groundDB?

**Comment by gadicc** [comment]
Never tested this scenario but don't see any problems.

In the current version translations come in through regular subscriptions, so should work fine with grounddb.  (Appcache is used by a number of our users and works fine).

In the next version, we'll handle all our own caching, so will work offline even without grounddb.

See also in http://messageformat.meteor.com/docs#options `sendPolicy` can be `all` if you want all languages to be sent to the client on load (so they can change to "new" languages offline too).

**Comment by gadicc** [comment]
Is grounddb transparent to the app or does the app need to use appropriate hooks to work properly?

**Comment by almogdesign** [comment]
Its pretty much transparent you need to set "var groundBlocks = new Ground.Collection(Blocks);" and just call your sub / publish when the app loads or when you want to cache locally the data. 

I will give it a test now

**Comment by gadicc** [comment]
In that case I think you'll need to override the default collections... fortunately they'll all public :>

```js
mfPkg.mfStrings = new Ground.Collection("mfStrings");
mfPkg.mfMeta = new Ground.Collection("mfMeta");
```

(`mfRevisions` isn't really used beyond for keeping history)

Do that before `mfPkg.init()` and I think that might be all you need to do!  Maybe :)

**Comment by almogdesign** [comment]
I will give it a shot and see what happens, should take me about 10 / 20 min to test it out

**Comment by gadicc** [comment]
awesome! :)

**Comment by almogdesign** [comment]
@gadicc something I'm not clear about I have the following 
{{mf 'helloMessage' 'This string is translatable'}}

Were do I set the translation JSON file?

**Comment by gadicc** [comment]
No JSON :)

```bash
$ sudo npm install -g meteor-messageformat
$ mf_extract # in your project dir
```

Then go to `/translate` in your project to manage translations.

**Comment by almogdesign** [comment]
Yea I did that (I'm on local host), it seems that I can't add a language? also how do you set different languages

**Comment by almogdesign** [comment]
Attached image 
![screen shot 2015-03-03 at 6 30 14 pm](https://cloud.githubusercontent.com/assets/169507/6466927/9c0ac018-c1d3-11e4-8ebe-81a991e55353.png)

**Comment by gadicc** [comment]
Just type the translated string into the 2nd bottom box?
One screen back is the page that lets you add new languages.

**Comment by almogdesign** [comment]
So how does it save, it seems that it's always missing. Can you talk?

**Comment by gadicc** [comment]
Can't actually right now :(

Oh, umm, it saves whenever you move to the next translation (by clicking or using ctrl-up/down).  I guess I never thought of the case where there is only one translation in the entire project :)  I think just add one more translation and you should be good!

**Comment by almogdesign** [comment]
Ok let me test it out, also I'm going over the docs but I don't see how I set lang based on different user is there a method for this setLocal is throwing an error. 

Once it saves locally and I deploy to production, what happens if on production a user translates files?

**Comment by almogdesign** [comment]
@gadicc there is a major issue with the current way it saves. Your always missing the latest translation

**Comment by gadicc** [comment]
Mmm, we were screwing around with that a little, but basically, `Session.set('locale`, lang)` will work.

From the production site, just save /translate/mfAll.js to your project (there's a link on the translate page), that will update all the translations on devel.

Really?  Will look into that.  Basically as long as you navigate off a translation it should be saving.

**Comment by almogdesign** [comment]
@gadicc to understand everything message format is a bit more then a translation package like i18n it's a translation engine like Facebooks engine. 

As I developer I add my key string (using the helper or JavaScript) then run mf_extract push my app to production and there a user or someone from my team will translate everything online. 

Is that correct? 

Also each time I run "mf_extract" and update my app on production that will not delete current translations

**Comment by almogdesign** [comment]
@gadicc it doesn't really work, almost did. 

I did the following 
Ground.Collection(mfPkg.mfStrings);
Ground.Collection(mfPkg.mfMeta);
mfPkg.init('en', {sendPolicy:'all'});

And you can see the strings saved to the local storage 

However if your offline and do a page refresh, it loads only english and does not load the translation. I'm not sure if this is due to the session (but I do reset it on startup) or something else

**Comment by almogdesign** [comment]
@gadicc any ideas why it would not load the correct lang? It would be great to get this to work in offline mode.

**Comment by almogdesign** [comment]
Closing this an opening a new clean ticket

**Comment by gadicc** [comment]
Sorry, you caught me at quite a busy time but will try answer ASAP...

> @gadicc to understand everything message format is a bit more then a translation package like i18n it's a translation engine like Facebooks engine.  As I developer I add my key string (using the helper or JavaScript) then run mf_extract push my app to production and there a user or someone from my team will translate everything online.

Exactly (well, I never saw FB's engine but you described it perfectly :)).  Note also in the docs you can define allow rules for who can/cannot modify translations, by default it's any registered user.

> Also each time I run "mf_extract" and update my app on production that will not delete current translations

Correct.  mf_extract just keeps track of native strings.  If a string of an existing key is updated, the old version gets backed up to the mfRevisions collection, although currently there is no UI code to use it.  Translations are never affected (although in the next version they'll be marked as "fuzzy", i.e. the translation was made using an older source string).

Will reply to the other stuff in the new ticket.  Are you using GroundDB for the entire project or just for this?  I'm wondering how soon I can get a preview out of our next major version (which will have built in offline support), but I think it's going to be quite some time still :(

**Comment by almogdesign** [comment]
@gadicc this is actually very exciting but I have to tell you your message and what the package does it really not clear. I really think it needs a lot of work and can be improved. 

I would also suggest watching the Facebook Video about growth, the reason they built an "engine" was for growth which had a big impact.

Anyways I'm really excited about this package I haven't done any open source projects in Meteor yet it's a bit hard to do a project by myself with my current work load however I would be glad to help and join as a contributor. I can definitely help with marketing, message and building a community around the package. I can help with UI development, some of the core development and of course testing.
