### ISSUE TITLE
TypeError: Object #<Object> has no method 'page'

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#85]
When I click on Download server/mfAll.js  I'm getting the following error and of course noting happens 

W20150303-19:03:37.186(2)? (STDERR) TypeError: Object #<Object> has no method 'page'
W20150303-19:03:37.187(2)? (STDERR)     at [object Object].Router.route.name (app/lib/router.js:21:13)
W20150303-19:03:37.187(2)? (STDERR)     at packages/iron:router/lib/router.js:277:1
W20150303-19:03:37.188(2)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
W20150303-19:03:37.188(2)? (STDERR)     at [object Object].hookWithOptions (packages/iron:router/lib/router.js:276:1)
W20150303-19:03:37.188(2)? (STDERR)     at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1)
W20150303-19:03:37.188(2)? (STDERR)     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
W20150303-19:03:37.188(2)? (STDERR)     at packages/meteor/dynamics_nodejs.js:121:1
W20150303-19:03:37.188(2)? (STDERR)     at [object Object].dispatch (packages/iron:middleware-stack/lib/middleware_stack.js:275:1)
W20150303-19:03:37.188(2)? (STDERR)     at [object Object].RouteController._runRoute (packages/iron:router/lib/route_controller_server.js:63:1)
W20150303-19:03:37.188(2)? (STDERR)     at Function.Route.dispatch (packages/iron:router/lib/route.js:147:1)

**Comment by gadicc** [comment]
Just want to double check that you're on the latest v0.0.48 from last week; this sounds a lot like https://github.com/gadicc/meteor-messageformat/issues/81 that we fixed.

**Comment by almogdesign** [comment]
I'm have the following installed 
gadicohen:messageformat             0.0.48  MessageFormat support, the Meteor way

Also note I have tap:i18n installed (maybe their is a conflict?)

**Comment by gadicc** [comment]
Are you able to share the repo at all so I can take a look?  Or try give me a minimal reproduction?  I can't reproduce this on my side.  I don't think tap:i18n should cause any issues, this looks clearly like a routing issue.  We had a problem with this in the past, but the [workaround](https://github.com/gadicc/meteor-messageformat/blob/d155da3db9a95e035bd4682ff18cb158990b83ab/lib/mfPkg/messageformat-client.js#L357-L363) in the latest version solved it as far as I know (we avoid event propogation and handle the location change ourselves).

**Comment by almogdesign** [comment]
I removed tap:i18n I'm still getting this issue and I tried the workaround it did not work. I think it has to do with app cache and how it changes the url here is the info - https://github.com/gadicc/meteor-messageformat/issues/81

**Comment by gadicc** [comment]
Yes, I believe you're right.  I'll have to think how to avoid iron-router doing that.  Let's focus on getting the server side stuff working first though, as that's actually a show stopper for you.

**Comment by almogdesign** [comment]
@gadicc this is the same issue with the segment.io package conflict. I'm closing this to clean things up. #92 is correct one
