### ISSUE TITLE
Uncaught TypeError: Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#86]
Getting the following error, after installing the package and running the init command 
:3000/headersHelper.js?token=1425402425449.2417:1 Uncaught TypeError: Cannot read property 'headers' of undefined

Here is the header 
Package.headers.headers.store({"headers":{"host":"localhost:3000","connection":"keep-alive","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","accept-encoding":"gzip, deflate, sdch","accept-language":"en-US,en;q=0.8,he;q=0.6","x-forwarded-for":"127.0.0.1","x-forwarded-port":"3000","x-forwarded-proto":"http","x-ip-chain":"127.0.0.1,127.0.0.1"},"proxyCount":1});

**Comment by gadicc** [comment]
Just to confirm, this is part of the offline experiment, right?
Does meteor-headers work ok on it's own in this case?  It definitely used to :/

**Comment by almogdesign** [comment]
Both online and offline I'm getting this error

**Comment by almogdesign** [comment]
Is there an expected timeframe for this fix, I would like to use the package in production

**Comment by gadicc** [comment]
Sorry, you really did catch me at a bad time :(  Hope to get through all your queries in the first few days this week.

This issue you're experiencing is actually in `gadicohen:headers`, and was [fixed](https://github.com/gadicc/meteor-headers/issues/31) in v0.0.26 back in October last year.  Unfortunately `gadicohen:messageformat` only depends on headers v0.0.25.  Does running `meteor update` fix the issue for you?  Otherwise can you confirm versions of both packages from `meteor list` ?

**Comment by almogdesign** [comment]
No worries, due check my comments would be glad to join and help. 
Meteor updated did noting, meteor list does not show gadicohen:headers just gadicohen:messageformat ( 0.0.48 )

Should I manually add  gadicohen:headers

**Comment by gadicc** [comment]
Appreciate the patience!  Help would definitely be appreciated.. full reply on that coming soon.

Ah ok Meteor is getting too smart... let me just up that dep quick it will be easier and more sustainable solution.

**Comment by gadicc** [comment]
can you try `meteor update` now and see if it works?

**Comment by almogdesign** [comment]
Yep that worked, closing this. Now just need the offline mode to work. 

Changes to your project's package version selections from updating package versions:
                                              
gadicohen:headers        upgraded from 0.0.25 to 0.0.27
gadicohen:messageformat  upgraded from 0.0.48 to 0.0.49

**Comment by gadicc** [comment]
Great stuff, thanks for reporting back :)

Cool, you'll have my full attention on that tomorrow.

**Comment by almogdesign** [comment]
That would be great
