### ISSUE TITLE
Major issue message format not translating and is not reactive 

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#87]
Everything works fine when my app starts but on a page refresh I lose the translation even if set the session. Also if I update the session local the translation is not reactive. 

Here is my code 
```javascript
mfPkg.init('en'); // lib folder 
```

Client on startup I have the following 
```javascript
var setUserLanguage;
Meteor.startup(function () {
    setUserLanguage();
});

setUserLanguage = function () {
    Session.set("showLoadingIndicator", true);
    if(Meteor.user()){
        var lang = Meteor.user().profile.language;
        console.log('lang ' + lang);
        Session.set('locale', lang);
        Session.set("showLoadingIndicator", false);
    }
};

Tracker.autorun(function () {
    if(Meteor.user()){
        var lang = Meteor.users.find({_id: Meteor.user()._id});
        var handle = lang.observeChanges({
            changed: function (id, user) {
                setUserLanguage();
            }
        });
    }
});
```
  
The console.log is always - lang es

**Comment by almogdesign** [comment]
This seems to be fine once I added the following sendPolicy:'all'

**Comment by gadicc** [comment]
Is this still in your offline testing?  You shouldn't need `sendPolicy: "all"` for online usage; it should just take a little longer to switch languages.  If that's not the case, re-open so I can investigate.

**Comment by almogdesign** [comment]
When I tested without the sendPolicy all it was not saving the string to local storage

**Comment by almogdesign** [comment]
I'm re-oping

**Comment by gadicc** [comment]
That sounds right though... we don't use localStorage at all... so for offline usage you definitely want `sendPolicy: "all"`.  I had just wanted to check that for online, the switching works.  In the upcoming v2, even without sendPolicy:all, the user will still be able to switch between any language they've used before, since we will indeed be using localStorage.

**Comment by almogdesign** [comment]
Or great then I'm going to close this. Only feedback is if I have 15 languages and my user is ES there is no need to download and save all the strings which is a bit overkill. It would be nice if I can set which language to download.
