### ISSUE TITLE
Major issue when app is offline 

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#91]
If my app is in offline mode, not internet connection and it loads everything from app cache and groundDB I'm getting the following error message 

Resource interpreted as Script but transferred with MIME type text/html: "https://xstaging.goplatfarm.com/headersHelper.js?token=1425899998591.4875".
headersHelper.js?token=1425899998591.4875:1 Uncaught SyntaxError: Unexpected token <
4c603d60d86a8256c2320771323525a21c7300dd.js:32 

I'm not 100% sure whats casing it

**Comment by gadicc** [comment]
I'm going to answer this in the meteor-headers repo.
