### ISSUE TITLE
Server error when accessing translate/mfAll.js

### ISSUE THREAD

**Issue by gadicc** [gadicc/meteor-messageformat#92]
First mentioned in by @almogdesign in https://github.com/gadicc/meteor-messageformat/issues/81#issuecomment-77847227:

> I'm running into this issue, using the latest version and using iron-router. The following does not work 
Type in the URL /translate/mfAll.js by hand.

> and when I try Right click the link and click on Save As I get "failed server problem"

**Comment by gadicc** [comment]
@almogdesign, what's in the server logs when you try access this file?

**Comment by almogdesign** [comment]
Here is the server logs 

TypeError: Object #<Object> has no method 'page'
    at [object Object].Router.route.name (app/lib/router.js:21:13)
    at packages/iron:router/lib/router.js:277:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object].hookWithOptions (packages/iron:router/lib/router.js:276:1)
    at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1)
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
    at packages/meteor/dynamics_nodejs.js:121:1
    at [object Object].dispatch (packages/iron:middleware-stack/lib/middleware_stack.js:275:1)
    at [object Object].RouteController._runRoute (packages/iron:router/lib/route_controller_server.js:63:1)
    at Function.Route.dispatch (packages/iron:router/lib/route.js:147:1)

**Comment by almogdesign** [comment]
It happens when I try to access the page

**Comment by almogdesign** [comment]
@gadicc can I just manually add the route?

**Comment by gadicc** [comment]
Oh wow, I didn't realize these were your server logs.  In that case maybe it is the same issue... do you have any server-side route, or any route declared in both server/client js, that could be conflicting?

Possible untested quickfix... make sure messageformat is above iron:router in `.meteor/packages`.  It's weird that no one else had this issue server-side though.

**Comment by gadicc** [comment]
Also can you show me your `meteor list` again?  I can't reproduce this my side but maybe if I try the exact same iron:router versions as you.  And/or any chance of access to the repo to test against your code?  Particularly can you show me `app/lib/router.js` around line 21?

**Comment by almogdesign** [comment]
When I open the packages at .meteor I see that messageformat is above iron-router Here is a gist for the router - https://gist.github.com/almogdesign/a370b3046d4ff1f0ec69

I can share the repo or parts of it but I think the gist is faster

**Comment by gadicc** [comment]
Looks like it's the analytics stuff... if you disable the analytics page and/or comment out line 21, can you download the file by directly typing in the URL or right-clicking?

**Comment by almogdesign** [comment]
Ok fixed I comment outed and tested locally, testing on staging. This seems to be the issue with is the segment.io package  

// For page analytics
/*
Router.onRun(function() {
  analytics.page();
});
*/

**Comment by almogdesign** [comment]
I think an easy fix on your end is changing the route to mf-translation or something with a unique namespace so there will be no conflicts.

**Comment by gadicc** [comment]
Great, glad you have access to your translations!  Yeah this is something I'll consider, it's just annoying that it worked great for 2 yrs :)  Also not sure if the problem is with iron-router or analytics... it's possible analytics isn't working because iron-router isn't recognizing the route properly.  Will keep tracking this issue, at least now I know how to reproduce it.

**Comment by gadicc** [comment]
Cool, I gotta run... just wanted to make sure you could access the translations.  Good luck with client meeting!  Will be back later for other stuff.

**Comment by almogdesign** [comment]
All good just test it and working.
