### ISSUE TITLE
Resource interpreted as Script 

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#95]
When offline mode I'm getting the following error message not sure if this is affecting anything. 

Resource interpreted as Script but transferred with MIME type text/html: "https://xstaging.goplatfarm.com/headersHelper.js?token=1425982012935.465".

**Comment by gadicc** [comment]
I think this still relates to https://github.com/gadicc/meteor-headers/issues/37 which we can track in the meteor-headers repo.
