### ISSUE TITLE
mf_extract doesn't pick up mf(key, text) with no middle `params` arg

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#97]
I have the following 

 var formSuccessfully = mf('formSavedToDB', 'Form successfully saved to database.');
 throwAppNotification(formSuccessfully, 'success');

When I run mf_extract and then check mfExtract.JS I'm not seeing "formSavedToDB". 

Also if I try the following 
throwAppNotification(mf('formSavedToDB', 'Form successfully saved to database.'), 'success');

it picks up the key but uses success as the mf text which is incorrect.

**Comment by gadicc** [comment]
Mmm, is that in the root of the file?  On client or server?  mf_extract only actually checks in functions, that's maybe a lack of foresight on my part, but usually we only call `mf()` from inside a function since we need to dynamically know what language to translate too.

**Comment by almogdesign** [comment]
@gadicc it's both server and client I am calling from a function  here is an example 
```javascript
Meteor.call('formInsert', formName, producerName, location, formTemplate, producerId, blockId, blockUnitCodeSubCode, formData,  getLocale(), function(error, result) {
                // display the error to the user and abort
                if (error)
                    return throwAppNotification(error.reason, 'danger');
                if(result) {
                    var formSuccessfully = mf('formSavedToDB', 'Form successfully saved to database.');
                    throwAppNotification(formSuccessfully, 'success');
                    Router.go('forms');
                }
            });
```

I also note if I try the following, it does not work it things 'success' is the text to be translated 
 ```javascript  
throwAppNotification(mf('formSavedToDB', 'Form successfully saved to database.'), 'success');
```

**Comment by gadicc** [comment]
Ok, thanks for sample code.  Sounds like a bug.  Will try my best to get to this before the weekend and get a fix out.

**Comment by almogdesign** [comment]
No problem, do you need an example from the server side?

**Comment by gadicc** [comment]
Hey, can you confirm if v0.0.50 solves your problem?   I hope it does since I'm leaving soon to go away for the weekend :>  Otherwise in case not, the following also works, changing:

```js
var formSuccessfully = mf('formSavedToDB', 'Form successfully saved to database.');
```
to
```js
var formSuccessfully = mf('formSavedToDB', null, 'Form successfully saved to database.');
```

But v0.0.50 should recognize the former perfectly now, which really is supported by the mf() API and should have been supported by mf_extract too.

**Comment by almogdesign** [comment]
Fixed everything is working now thanks
