### ISSUE TITLE
meteor add gadicc:messageformat: no such package

### ISSUE THREAD

**Issue by brylie** [gadicc/meteor-messageformat#98]
Will this be, or is it already, packaged for Meteor >= 0.9? E.g. I am trying to install via the command `meteor add gadicc:messageformat` instead of using `mrt`. If this has already been resolved, it may be worthwhile to update the [quickstart documentation](http://messageformat.meteor.com/docs#quickstart).

**Comment by brylie** [comment]
I just found the [gadicohen:messageformat](https://atmospherejs.com/gadicohen/messageformat) package on atmosphere. Is this the recommended package?

**Comment by dcsan** [comment]
looking at the [package.js](https://github.com/gadicc/meteor-messageformat/blob/v0/package.js) in this repo that does seem to be the case, i guess gadi updated his namespace.

**Comment by gadicc** [comment]
Yes, `gadicohen:messageformat` is the official package.  Thanks for figuring that out and updating the README, and thanks @dcsan for confirming.

I would *love* for it to be `gadicc:messageformat`, the same as my github, twitter and domain.  Name change support was promised just after 0.9 was released but hasn't arrived yet :>  Had I known I might have just created a new account and set-unmigrated the old packages... but at this stage I think it's just better to wait.

In any event, v2, when it is eventually released (no ETA for now), will be `msgfmt:core`, `msgfmt:ui`, `msgfmt:extract` etc.
